name: Run Tests
on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
env:
    REPO_URL: https://github.com/AndersonOlarte/CursoTestingReto4.git
    WORKING_DIR: CursoTestingReto4
jobs:
    run-tests:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Flask app repo 
              uses: actions/checkout@v3
            
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.11'

            - name: Install Flask app dependencies
              run: |
                python -m venv venv
                source venv/bin/activate
                pip install -r requirements.txt

            - name: Run Flask app
              run: |
                source venv/bin/activate
                flask initdb
                flask translate compile
                nohup flask run --host=0.0.0.0 > flask.log 2>&1 &
                sleep 5  # Espera a que la aplicación inicie
                # Verificar que la aplicación está corriendo
                if ! curl -s http://localhost:5000 >/dev/null; then
                  echo "La aplicación Flask no está corriendo. Mostrando logs:"
                  cat flask.log
                  exit 1
                else
                  echo "La aplicación Flask está corriendo correctamente."
                fi

            - name: Checkout tests repo
              run: git clone $REPO_URL

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                node-version: lts/*

            - name: Install dependencies
              run: |
                ls -al
                cd $WORKING_DIR
                npm ci

            - name: Install Playwright Browsers
              run: npx playwright install --with-deps

            - name: Run Playwright Test
              run: |
                cd $WORKING_DIR
                echo "Ejecución de pruebas en todo LIST"
                npx playwright test todotesting.spec.ts --trace on --timeout=60000

            - name: Upload Artifact
              uses: actions/upload-artifact@v4
              if: ${{ !cancelled() }}
              with:
                name: $WORKING_DIR
                path: $WORKING_DIR/playwright-report/
                retention-days: 30